name: song_recommendation_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - streamlit=0.88.0
  - scikit-learn
  - pandas
  - jupyterlab  # Add JupyterLab
  - ipykernel   # Add ipykernel to manage kernels
  - pip  # Include pip so that we can use it to install Spotipy
  - spotipy